name: Selenium Tests CI

on:
  push:
    branches:
      - main
      - master

  pull_request:
    branches:
      - main
      - master

jobs:

  selenium-tests:

    runs-on: ubuntu-latest

    steps:

      # ==================================================
      # Descargar repositorio
      # ==================================================

      - name: Checkout repository
        uses: actions/checkout@v4

      # ==================================================
      # Instalar Python
      # ==================================================

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'

      # ==================================================
      # Instalar dependencias
      # ==================================================

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r "Fase 6/requirements.txt"

      # ==================================================
      # Instalar Google Chrome
      # ==================================================

      - name: Install Chrome
        uses: browser-actions/setup-chrome@v1

      # ==================================================
      # Ejecutar pruebas
      # ==================================================

      - name: Run Selenium Tests
        run: |
          pytest "Fase 6/" --html=reporte_pruebas.html --self-contained-html

      # ==================================================
      # Guardar reporte HTML
      # ==================================================

      - name: Upload HTML Report
        uses: actions/upload-artifact@v4
        with:
          name: reporte-pruebas
          path: reporte_pruebas.html